#配置数据源
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/huamall?useUnicode=true&characterEncoding=utf8
      username: root
      password: root
      max-active: 20
      max-wait: 5000
      initial-size: 1

    #监控配置
#修改端口号为8088
server:
  port: 8089

swagger:
  host: localhost:8089
  title: SpringBoot 整合 Swagger2
  description: 网站描述
  disabled: false # 是否禁用swagger
  redirect-uri: / # 禁用swagger时的重定向地址
project:
  version: 1.0